# .github/workflows/ci-cd.yml

name: Django CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      # 3. Cache Pipenv dependencies to speed up builds
      - name: Cache Pipenv Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      # 4. Install dependencies using Pipenv
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --ignore-pipfile

      # 5. Run Django tests
      - name: Run Tests
        run: pipenv run python manage.py test

      # 6. Collect static files
      - name: Collect Static Files
        run: pipenv run python manage.py collectstatic --noinput

      # 7. Upload Test Results (Optional)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TEST-*.xml'

      # 8. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # Name of your Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP }}  # Publish profile stored as a secret
          package: .  # Path to your application package (current directory)

      # 9. Optional: Notify Deployment Status
      - name: Notify Deployment Status
        if: success()
        run: echo "Deployment to Azure Web App succeeded!"
